---

boot_config:
  max_usb_current: 1
  hdmi_group: 2
  hdmi_mode: 87
  hdmi_drive: 1
  dtoverlay: gpio-shutdown

boot_config_lines:
  - "hdmi_cvt 1024 600 60 6 0 0 0"
  - "gpio=17=op,dh"

openbox_config:
  - { xpath: "x:desktops/x:number", value: "2" }
  - { xpath: "x:desktops/x:popupTime", value: "0" }